# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from Code.optionsWindow import Ui_optionsWindow
from PyQt6.QtWidgets import QLabel

class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_optionsWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Create Label object for the title
        self.label = QLabel(parent=self.centralwidget)
        self.label.setText("Nombre App")
        self.label.setGeometry(QtCore.QRect(130, 50, 200, 30))

        # Asign the initial vertical position for names
        y_pos = 150

        # Create a lable for each name
        for nombre in ["-Emilio Sebastián Chavez Vega", "-Ulises Andrade Gonzalez",
                       "-Luis Angel Quijano Guerrero", "-Erick Martín Morín Lopez"]:
            label = QLabel(parent=self.centralwidget)
            label.setText(nombre)
            label.setGeometry(QtCore.QRect(100, y_pos, 200, 30))
            y_pos += 30  # the vertical position is adjusted for each label

        # Select the Font and Size
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget, clicked = lambda: self.openWindow()) # opens window
        self.pushButton.setGeometry(QtCore.QRect(200, 500, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")

        # Create the Exit button
        self.pushButtonSalir = QtWidgets.QPushButton(parent=self.centralwidget, text="Salir", clicked=MainWindow.close)
        self.pushButtonSalir.setGeometry(QtCore.QRect(75, 500, 100, 30))
        self.pushButtonSalir.setFont(font)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
