# Form implementation generated from reading ui file 'options.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_optionsWindow(object):
    def setupUi(self, optionsWindow):
        optionsWindow.setObjectName("optionsWindow")
        optionsWindow.resize(388, 600)
        self.centralwidget = QtWidgets.QWidget(parent=optionsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 171, 31))
        self.label.setObjectName("label")
        optionsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=optionsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 388, 22))
        self.menubar.setObjectName("menubar")
        optionsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=optionsWindow)
        self.statusbar.setObjectName("statusbar")
        optionsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(optionsWindow)
        QtCore.QMetaObject.connectSlotsByName(optionsWindow)

    def retranslateUi(self, optionsWindow):
        _translate = QtCore.QCoreApplication.translate
        optionsWindow.setWindowTitle(_translate("optionsWindow", "MainWindow"))
        self.label.setText(_translate("optionsWindow", "Select an option:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    optionsWindow = QtWidgets.QMainWindow()
    ui = Ui_optionsWindow()
    ui.setupUi(optionsWindow)
    optionsWindow.show()
    sys.exit(app.exec())
